### ISSUE TITLE
Atualizar o readme do npm

### ISSUE THREAD

**Issue by brenonaraujo** [dev-senior-com-br/multischemase#4]
O readme atual ainda referes-se a versão anterior da lib a qual possuía dependências da JVM e do maven no ambiente, é importante manter o readme do npm atualizado.

https://www.npmjs.com/package/multischemase
![Screen Shot 2020-07-04 at 03 13 06](https://user-images.githubusercontent.com/8471549/86506273-4baaea80-bda4-11ea-957f-571a3aa5ca32.png)

**Comment by wallacetm** [comment]
Corrigido: https://www.npmjs.com/package/@seniorsistemas/multischemase
